spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/lifts_manager_db?createDatabaseIfNotExist=true
    #url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/lifts_manager_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8082
    
logging:
  level:
    org.springframework: INFO
